version: 2.1

orbs:
  win: circleci/windows@2.2.0

defaults:

  # --------------------------------------------------------------------------
  # Artifacts Templates

  # the whole build directory
  - artifacts_build_dir: &artifacts_build_dir
      root: build
      paths:
        - "*"

  # compiled solc executable target
  - artifacts_solc: &artifacts_solc
      path: build/solc/solc
      destination: solc

  # windows artifacts
  - artifact_solc_windows: &artifact_solc_windows
      path: upload/

  # compiled tool executable target
  - artifacts_tools: &artifacts_tools
      path: build/tools/solidity-upgrade
      destination: solidity-upgrade

  # compiled executable targets
  - artifacts_executables: &artifacts_executables
      root: build
      paths:
        - solc/solc
        - test/soltest
        - test/tools/solfuzzer

  # compiled OSSFUZZ targets
  - artifacts_executables_ossfuzz: &artifacts_executables_ossfuzz
      root: build
      paths:
        - test/tools/ossfuzz/abiv2_proto_ossfuzz
        - test/tools/ossfuzz/abiv2_isabelle_ossfuzz
        - test/tools/ossfuzz/const_opt_ossfuzz
        - test/tools/ossfuzz/solc_mutator_ossfuzz
        - test/tools/ossfuzz/solc_ossfuzz
        - test/tools/ossfuzz/stack_reuse_codegen_ossfuzz
        - test/tools/ossfuzz/strictasm_assembly_ossfuzz
        - test/tools/ossfuzz/strictasm_diff_ossfuzz
        - test/tools/ossfuzz/strictasm_opt_ossfuzz
        - test/tools/ossfuzz/yul_proto_diff_ossfuzz
        - test/tools/ossfuzz/yul_proto_diff_custom_mutate_ossfuzz
        - test/tools/ossfuzz/yul_proto_ossfuzz
        - test/tools/ossfuzz/sol_proto_ossfuzz

  # test result output directory
  - artifacts_test_results: &artifacts_test_results
      path: test_results/
      destination: test_results/

  # --------------------------------------------------------------------------
  # Workflow Templates

  - workflow_trigger_on_tags: &workflow_trigger_on_tags
      filters:
        tags:
          only: /.*/

# -----------------------------------------------------------------------------------------------
jobs:


  b_osx:
    macos:
      xcode: "11.0.0"
    environment:
      TERM: xterm
      CMAKE_BUILD_TYPE: Release
      MAKEFLAGS: -j 5
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-osx-{{ checksum ".circleci/osx_install_dependencies.sh" }}
      # DO NOT EDIT between here and save_cache, but rather edit ./circleci/osx_install_dependencies.sh
      # WARNING! If you do edit anything here instead, remember to invalidate the cache manually.
      - run:
          name: Install build dependencies
          command: ./.circleci/osx_install_dependencies.sh
      - save_cache:
          key: dependencies-osx-{{ checksum ".circleci/osx_install_dependencies.sh" }}
          paths:
            - /usr/local/bin
            - /usr/local/sbin
            - /usr/local/lib
            - /usr/local/include
            - /usr/local/Cellar
            - /usr/local/Homebrew
      - run: *run_build
      - store_artifacts: *artifacts_solc
      - store_artifacts: *artifacts_tools
      - persist_to_workspace:
          root: .
          paths:
            - build/solc/solc
            - build/test/soltest
            - build/test/tools/solfuzzer
            
workflows:
  version: 2

  main:
    jobs:
      # OS/X build and tests
      - b_osx: *workflow_trigger_on_tags
